# Generated by Django 3.2.21 on 2023-11-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
    ]
